### ISSUE TITLE
谁给你们随便封人的权力？

### ISSUE THREAD

**Issue by singer01** [MrZhang365/ZhangBlog#1]
打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！

**Comment by MrZhang365** [comment]
请阅读这个 [Issue](https://github.com/MrZhang365/HC-Plus/issues/1)
